import { collection, doc, setDoc } from "firebase/firestore";
import { db } from "./firebaseConfig/firebaseConfig";
const products = [
  {
    id: 1,
    name: "Apple iPhone 14 Pro",
    img: "https://m.media-amazon.com/images/I/61XO4bORHUL._AC_SL1500_.jpg",
    category: "Electronics",
    subcategory: "Smartphones",
    price: 999,
    description:
      "The latest iPhone with a powerful A16 chip and a stunning Dynamic Island.",
    brand: "Apple",
    rating: 4.8,
    reviews: 1000,
    stock: 50,
    colors: ["Space Black", "Silver", "Gold", "Deep Purple"],
    storage: ["128GB", "256GB", "512GB", "1TB"],
  },
  {
    id: 2,
    name: "Samsung Galaxy S23 Ultra",
    img: "https://m.media-amazon.com/images/I/71Sa3dqTqGL._AC_SL1500_.jpg",
    category: "Electronics",
    subcategory: "Smartphones",
    price: 1199,
    description:
      "The ultimate Android smartphone with a powerful camera and S Pen.",
    brand: "Samsung",
    rating: 4.7,
    reviews: 800,
    stock: 30,
    colors: ["Phantom Black", "Cream", "Green", "Lavender"],
    storage: ["256GB", "512GB", "1TB"],
  },
  {
    id: 3,
    name: "Sony WH-1000XM5",
    img: "https://m.media-amazon.com/images/I/61+btxzpfDL._AC_SL1500_.jpg",
    category: "Electronics",
    subcategory: "Headphones",
    price: 399,
    description:
      "Industry-leading noise-canceling headphones with exceptional sound quality.",
    brand: "Sony",
    rating: 4.9,
    reviews: 2000,
    stock: 100,
    colors: ["Black", "Silver", "Platinum Silver"],
  },
  {
    id: 4,
    name: "Apple Watch Series 8",
    img: "https://m.media-amazon.com/images/I/71ulah9iAAL._AC_SL1500_.jpg",
    category: "Electronics",
    subcategory: "Smartwatches",
    price: 399,
    description:
      "The latest Apple Watch with advanced health and fitness features.",
    brand: "Apple",
    rating: 4.6,
    reviews: 1500,
    stock: 70,
    colors: ["Midnight", "Starlight", "Silver", "Product Red"],
  },
  {
    id: 5,
    name: "Nintendo Switch OLED",
    img: "https://m.media-amazon.com/images/I/71mTPU5+RWL._SL1500_.jpg",
    category: "Gaming",
    subcategory: "Consoles",
    price: 349,
    description: "The upgraded Switch with a vibrant OLED display.",
    brand: "Nintendo",
    rating: 4.8,
    reviews: 3000,
    stock: 20,
    colors: ["White", "Neon Red", "Neon Blue"],
  },
  {
    id: 6,
    name: "PlayStation 5",
    img: "https://m.media-amazon.com/images/I/51051FiD9UL._SL1500_.jpg",
    category: "Gaming",
    subcategory: "Consoles",
    price: 499,
    description:
      "The latest PlayStation console with stunning graphics and fast loading times.",
    brand: "Sony",
    rating: 4.7,
    reviews: 2500,
    stock: 5,
    colors: ["White"],
  },
  {
    id: 7,
    name: "Xbox Series X",
    img: "https://m.media-amazon.com/images/I/61JGKhqxHxL._SL1500_.jpg",
    category: "Gaming",
    subcategory: "Consoles",
    price: 499,
    description:
      "The most powerful Xbox console with 4K gaming and ray tracing.",
    brand: "Microsoft",
    rating: 4.6,
    reviews: 2000,
    stock: 10,
    colors: ["Black"],
  },
  {
    id: 8,
    name: "Logitech G Pro X Superlight",
    img: "https://m.media-amazon.com/images/I/61IYYoZ66VL._AC_SL1500_.jpg",
    category: "Gaming",
    subcategory: "Mice",
    price: 149,
    description:
      "The lightest wireless gaming mouse with incredible performance.",
    brand: "Logitech",
    rating: 4.9,
    reviews: 1000,
    stock: 50,
    colors: ["Black", "White"],
  },
  {
    id: 9,
    name: "Razer Viper Ultimate",
    img: "https://m.media-amazon.com/images/I/61MI2KPnupL._AC_SL1500_.jpg",
    category: "Gaming",
    subcategory: "Mice",
    price: 149,
    description:
      "A fast and accurate wireless gaming mouse with a sleek design.",
    brand: "Razer",
    rating: 4.8,
    reviews: 800,
    stock: 30,
    colors: ["Black", "Mercury White"],
  },
  {
    id: 10,
    name: "HyperX Cloud Alpha S",
    img: "https://m.media-amazon.com/images/I/71S-wNPdxqL._AC_SL1500_.jpg",
    category: "Gaming",
    subcategory: "Headsets",
    price: 99,
    description:
      "A comfortable gaming headset with excellent sound quality and a durable build.",
    brand: "HyperX",
    rating: 4.7,
    reviews: 1500,
    stock: 80,
    colors: ["Black", "Red"],
  },
  {
    id: 11,
    name: "AirPods Pro (2nd generation)",
    img: "https://m.media-amazon.com/images/I/61f1YfTkTDL._AC_SL1500_.jpg",
    category: "Electronics",
    subcategory: "Earbuds",
    price: 249,
    description:
      "Premium wireless earbuds with active noise cancellation and adaptive EQ.",
    brand: "Apple",
    rating: 4.8,
    reviews: 2000,
    stock: 120,
    colors: ["White"],
  },
  {
    id: 12,
    name: "Samsung Galaxy Buds2 Pro",
    img: "https://m.media-amazon.com/images/I/61Qqg+T8nsL._AC_SL1500_.jpg",
    category: "Electronics",
    subcategory: "Earbuds",
    price: 199,
    description: "High-fidelity audio with powerful active noise cancellation.",
    brand: "Samsung",
    rating: 4.7,
    reviews: 1000,
    stock: 90,
    colors: ["Bora Purple", "Graphite", "White"],
  },
  {
    id: 13,
    name: "Bose QuietComfort Earbuds II",
    img: "https://m.media-amazon.com/images/I/61QYbR8pThL._AC_SL1500_.jpg",
    category: "Electronics",
    subcategory: "Earbuds",
    price: 299,
    description:
      "The best noise-canceling earbuds with exceptional sound quality.",
    brand: "Bose",
    rating: 4.9,
    reviews: 1500,
    stock: 70,
    colors: ["Triple Black", "Soapstone"],
  },
  {
    id: 14,
    name: "Sony PlayStation 5 DualSense Wireless Controller",
    img: "https://m.media-amazon.com/images/I/61O9tWR6WDS._SL1500_.jpg",
    category: "Gaming",
    subcategory: "Controllers",
    price: 69,
    description:
      "The official controller for PlayStation 5 with adaptive triggers and haptic feedback.",
    brand: "Sony",
    rating: 4.8,
    reviews: 1200,
    stock: 150,
    colors: ["Midnight Black", "Cosmic Red", "Nova Pink", "Starlight Blue"],
  },
  {
    id: 15,
    name: "Xbox Wireless Controller",
    img: "https://m.media-amazon.com/images/I/61z3GQgEPZL._SL1500_.jpg",
    category: "Gaming",
    subcategory: "Controllers",
    price: 59,
    description:
      "The official controller for Xbox Series X|S with a comfortable grip and share button.",
    brand: "Microsoft",
    rating: 4.7,
    reviews: 1000,
    stock: 100,
    colors: [
      "Carbon Black",
      "Robot White",
      "Shock Blue",
      "Pulse Red",
      "Electric Volt",
    ],
  },
  {
    id: 16,
    name: "Dell XPS 13 Laptop",
    img: "https://m.media-amazon.com/images/I/71QR0MJkQxL._AC_SL1500_.jpg",
    category: "Electronics",
    subcategory: "Laptops",
    price: 1299,
    description:
      "A sleek and powerful ultrabook with a stunning InfinityEdge display.",
    brand: "Dell",
    rating: 4.8,
    reviews: 900,
    stock: 25,
    colors: ["Platinum Silver", "Frost White"],
  },
  {
    id: 17,
    name: 'Apple MacBook Pro 16"',
    img: "https://m.media-amazon.com/images/I/61fd2oCrvyL._AC_SL1500_.jpg",
    category: "Electronics",
    subcategory: "Laptops",
    price: 2499,
    description:
      "The ultimate laptop for professionals, featuring the powerful M2 Pro chip.",
    brand: "Apple",
    rating: 4.9,
    reviews: 1200,
    stock: 15,
    colors: ["Space Gray", "Silver"],
  },
  {
    id: 18,
    name: 'Samsung QLED Smart TV 55"',
    img: "https://m.media-amazon.com/images/I/81+qYQH1LiL._AC_SL1500_.jpg",
    category: "Electronics",
    subcategory: "Televisions",
    price: 799,
    description:
      "A stunning 4K QLED TV with vibrant colors and smart features.",
    brand: "Samsung",
    rating: 4.7,
    reviews: 1500,
    stock: 40,
    colors: ["Black"],
  },
  {
    id: 19,
    name: 'Sony Bravia OLED TV 65"',
    img: "https://m.media-amazon.com/images/I/81qKPxF8VhL._AC_SL1500_.jpg",
    category: "Electronics",
    subcategory: "Televisions",
    price: 1999,
    description:
      "A premium OLED TV with unparalleled picture quality and sound.",
    brand: "Sony",
    rating: 4.9,
    reviews: 1000,
    stock: 10,
    colors: ["Black"],
  },
  {
    id: 20,
    name: "GoPro HERO11 Black",
    img: "https://m.media-amazon.com/images/I/61PNB5hZpWL._AC_SL1500_.jpg",
    category: "Electronics",
    subcategory: "Cameras",
    price: 499,
    description:
      "The most powerful GoPro ever with 5.3K video and HyperSmooth stabilization.",
    brand: "GoPro",
    rating: 4.8,
    reviews: 500,
    stock: 60,
    colors: ["Black"],
  },
  {
    id: 21,
    name: "Canon EOS R5 Mirrorless Camera",
    img: "https://m.media-amazon.com/images/I/71hsvQyHBZL._AC_SL1500_.jpg",
    category: "Electronics",
    subcategory: "Cameras",
    price: 3899,
    description:
      "A high-performance camera for professionals with 45MP and 8K video.",
    brand: "Canon",
    rating: 4.9,
    reviews: 300,
    stock: 20,
    colors: ["Black"],
  },
  {
    id: 22,
    name: "NVIDIA GeForce RTX 4090",
    img: "https://m.media-amazon.com/images/I/81FGpYuDJYL._AC_SL1500_.jpg",
    category: "Electronics",
    subcategory: "Graphics Cards",
    price: 1599,
    description: "The most powerful GPU for gaming and creative work.",
    brand: "NVIDIA",
    rating: 4.9,
    reviews: 800,
    stock: 30,
    colors: ["Black"],
  },
  {
    id: 23,
    name: "Asus ROG Zephyrus G14",
    img: "https://m.media-amazon.com/images/I/71YN5eKhqQL._AC_SL1500_.jpg",
    category: "Electronics",
    subcategory: "Laptops",
    price: 1699,
    description:
      "A gaming laptop with powerful AMD Ryzen processors and NVIDIA RTX graphics.",
    brand: "Asus",
    rating: 4.8,
    reviews: 600,
    stock: 20,
    colors: ["Eclipse Gray", "Moonlight White"],
  },
  {
    id: 24,
    name: "Alienware Aurora R15",
    img: "https://m.media-amazon.com/images/I/71DSxfKzkFL._AC_SL1500_.jpg",
    category: "Electronics",
    subcategory: "Desktops",
    price: 2499,
    description:
      "A premium gaming desktop with cutting-edge performance and stunning design.",
    brand: "Alienware",
    rating: 4.8,
    reviews: 500,
    stock: 15,
    colors: ["Dark Side of the Moon"],
  },
  {
    id: 25,
    name: "Razer Blade 15",
    img: "https://m.media-amazon.com/images/I/71Cj5hpQKGL._AC_SL1500_.jpg",
    category: "Electronics",
    subcategory: "Laptops",
    price: 2399,
    description: "A sleek gaming laptop with a 240Hz display and RTX 3080 Ti.",
    brand: "Razer",
    rating: 4.9,
    reviews: 700,
    stock: 25,
    colors: ["Black", "Mercury White"],
  },
  {
    id: 26,
    name: "Dyson V15 Detect Vacuum Cleaner",
    img: "https://m.media-amazon.com/images/I/71s0JG+YdFL._AC_SL1500_.jpg",
    category: "Home Appliances",
    subcategory: "Vacuum Cleaners",
    price: 699,
    description:
      "A smart vacuum cleaner with laser detection and powerful suction.",
    brand: "Dyson",
    rating: 4.9,
    reviews: 1000,
    stock: 50,
    colors: ["Yellow", "Silver"],
  },
  {
    id: 27,
    name: "iRobot Roomba i7+",
    img: "https://m.media-amazon.com/images/I/71Sp6ChXSbL._AC_SL1500_.jpg",
    category: "Home Appliances",
    subcategory: "Vacuum Cleaners",
    price: 799,
    description:
      "A smart robot vacuum with automatic dirt disposal and mapping.",
    brand: "iRobot",
    rating: 4.8,
    reviews: 900,
    stock: 40,
    colors: ["Black"],
  },
  {
    id: 28,
    name: 'LG C2 OLED TV 55"',
    img: "https://m.media-amazon.com/images/I/81LHxfnXzHL._AC_SL1500_.jpg",
    category: "Electronics",
    subcategory: "Televisions",
    price: 1299,
    description:
      "A stunning OLED TV with Dolby Vision IQ and gaming optimization.",
    brand: "LG",
    rating: 4.9,
    reviews: 1100,
    stock: 25,
    colors: ["Black"],
  },
  {
    id: 29,
    name: "Microsoft Surface Laptop Studio",
    img: "https://m.media-amazon.com/images/I/71xb7xWlkCL._AC_SL1500_.jpg",
    category: "Electronics",
    subcategory: "Laptops",
    price: 1599,
    description:
      "A versatile laptop with a dynamic touchscreen and excellent performance.",
    brand: "Microsoft",
    rating: 4.8,
    reviews: 400,
    stock: 30,
    colors: ["Platinum"],
  },
  {
    id: 30,
    name: "Samsung Galaxy Tab S9 Ultra",
    img: "https://m.media-amazon.com/images/I/81a+qcKFQeL._AC_SL1500_.jpg",
    category: "Electronics",
    subcategory: "Tablets",
    price: 1199,
    description:
      "A high-performance tablet with a stunning AMOLED display and S Pen.",
    brand: "Samsung",
    rating: 4.9,
    reviews: 500,
    stock: 50,
    colors: ["Graphite"],
  },
  {
    id: 31,
    name: "Nike Air Zoom Pegasus 40",
    img: "https://m.media-amazon.com/images/I/71jeoX0rMRL._AC_SL1500_.jpg",
    category: "Clothing",
    subcategory: "Footwear",
    price: 130,
    description:
      "A versatile running shoe with lightweight cushioning and a responsive feel.",
    brand: "Nike",
    rating: 4.8,
    reviews: 1200,
    stock: 70,
    colors: ["Black", "White", "Blue", "Red"],
  },
  {
    id: 32,
    name: "Adidas Ultraboost 22",
    img: "https://m.media-amazon.com/images/I/71cllqoE3EL._AC_SL1500_.jpg",
    category: "Clothing",
    subcategory: "Footwear",
    price: 190,
    description:
      "A premium running shoe with energy-returning Boost technology.",
    brand: "Adidas",
    rating: 4.9,
    reviews: 1500,
    stock: 50,
    colors: ["Core Black", "Cloud White", "Solar Red"],
  },
  {
    id: 33,
    name: "Levi's 501 Original Fit Jeans",
    img: "https://m.media-amazon.com/images/I/91J9X69+GlL._AC_SL1500_.jpg",
    category: "Clothing",
    subcategory: "Jeans",
    price: 90,
    description:
      "The classic Levi's jeans with a straight-leg design and durable fabric.",
    brand: "Levi's",
    rating: 4.7,
    reviews: 800,
    stock: 100,
    colors: ["Blue Denim", "Black", "Gray"],
  },
  {
    id: 34,
    name: "Under Armour Tech 2.0 T-Shirt",
    img: "https://m.media-amazon.com/images/I/51JdzGhwB7L._AC_SL1000_.jpg",
    category: "Clothing",
    subcategory: "T-Shirts",
    price: 25,
    description:
      "A lightweight and breathable workout shirt with sweat-wicking technology.",
    brand: "Under Armour",
    rating: 4.8,
    reviews: 600,
    stock: 200,
    colors: ["Black", "White", "Red", "Navy Blue"],
  },
  {
    id: 35,
    name: "Columbia Ascender Softshell Jacket",
    img: "https://m.media-amazon.com/images/I/91ZwQWgx7rL._AC_SL1500_.jpg",
    category: "Clothing",
    subcategory: "Jackets",
    price: 70,
    description:
      "A water-resistant softshell jacket perfect for outdoor adventures.",
    brand: "Columbia",
    rating: 4.9,
    reviews: 900,
    stock: 80,
    colors: ["Black", "Gray", "Navy Blue"],
  },
  {
    id: 36,
    name: "Patagonia Nano Puff Jacket",
    img: "https://m.media-amazon.com/images/I/71dOD4CwJXL._AC_SL1500_.jpg",
    category: "Clothing",
    subcategory: "Jackets",
    price: 229,
    description:
      "A lightweight and insulated jacket for chilly weather and travel.",
    brand: "Patagonia",
    rating: 4.8,
    reviews: 700,
    stock: 50,
    colors: ["Forge Gray", "Classic Navy", "Black"],
  },
  {
    id: 37,
    name: "The North Face Borealis Backpack",
    img: "https://m.media-amazon.com/images/I/71YFlMT5RKL._AC_SL1500_.jpg",
    category: "Accessories",
    subcategory: "Bags",
    price: 99,
    description: "A durable and versatile backpack for daily use or travel.",
    brand: "The North Face",
    rating: 4.9,
    reviews: 1200,
    stock: 150,
    colors: ["Black", "Blue", "Gray", "Green"],
  },
  {
    id: 38,
    name: "Ray-Ban Aviator Sunglasses",
    img: "https://m.media-amazon.com/images/I/61QvUOFYxBL._AC_SL1500_.jpg",
    category: "Accessories",
    subcategory: "Sunglasses",
    price: 170,
    description:
      "Iconic aviator sunglasses with polarized lenses and a timeless design.",
    brand: "Ray-Ban",
    rating: 4.9,
    reviews: 1300,
    stock: 80,
    colors: [
      "Gold Frame/Green Lens",
      "Silver Frame/Blue Lens",
      "Black Frame/Gray Lens",
    ],
  },
  {
    id: 39,
    name: "Gucci GG Marmont Mini Bag",
    img: "https://m.media-amazon.com/images/I/61y+KQJKpbL._AC_SL1500_.jpg",
    category: "Accessories",
    subcategory: "Bags",
    price: 1500,
    description: "A luxurious crossbody bag with the iconic GG logo.",
    brand: "Gucci",
    rating: 4.8,
    reviews: 400,
    stock: 20,
    colors: ["Black", "White", "Beige"],
  },
  {
    id: 40,
    name: "Lululemon Align High-Rise Leggings",
    img: "https://m.media-amazon.com/images/I/71YqXoZ15NL._AC_SL1500_.jpg",
    category: "Clothing",
    subcategory: "Leggings",
    price: 98,
    description:
      "Soft and stretchy leggings designed for yoga and casual wear.",
    brand: "Lululemon",
    rating: 4.9,
    reviews: 2000,
    stock: 150,
    colors: ["Black", "Gray", "Pink", "Navy"],
  },
  {
    id: 41,
    name: "H&M Slim Fit Shirt",
    img: "https://m.media-amazon.com/images/I/61+-CgkBTuL._AC_SL1500_.jpg",
    category: "Clothing",
    subcategory: "Shirts",
    price: 25,
    description:
      "A stylish and slim-fit shirt perfect for formal or casual occasions.",
    brand: "H&M",
    rating: 4.7,
    reviews: 500,
    stock: 200,
    colors: ["White", "Light Blue", "Black"],
  },
  {
    id: 42,
    name: "Zara Basic Blazer",
    img: "https://m.media-amazon.com/images/I/61X3ftjRkML._AC_SL1500_.jpg",
    category: "Clothing",
    subcategory: "Blazers",
    price: 129,
    description: "A modern blazer with a tailored fit and versatile design.",
    brand: "Zara",
    rating: 4.8,
    reviews: 400,
    stock: 100,
    colors: ["Black", "Navy Blue", "Gray"],
  },
  {
    id: 43,
    name: "Puma Essentials Sweatpants",
    img: "https://m.media-amazon.com/images/I/71Qr+oV93rL._AC_SL1500_.jpg",
    category: "Clothing",
    subcategory: "Sweatpants",
    price: 40,
    description:
      "Comfortable and durable sweatpants for casual wear or workouts.",
    brand: "Puma",
    rating: 4.8,
    reviews: 800,
    stock: 200,
    colors: ["Black", "Gray", "Navy Blue"],
  },
  {
    id: 44,
    name: "Timberland 6-Inch Premium Boots",
    img: "https://m.media-amazon.com/images/I/71nNWbZPX5L._AC_SL1500_.jpg",
    category: "Clothing",
    subcategory: "Footwear",
    price: 198,
    description:
      "Iconic waterproof boots with premium leather and rugged durability.",
    brand: "Timberland",
    rating: 4.9,
    reviews: 1100,
    stock: 70,
    colors: ["Wheat", "Black", "Brown"],
  },
  {
    id: 45,
    name: "Champion Reverse Weave Hoodie",
    img: "https://m.media-amazon.com/images/I/71SBx7q7KvL._AC_SL1500_.jpg",
    category: "Clothing",
    subcategory: "Hoodies",
    price: 60,
    description:
      "A classic hoodie with a soft interior and iconic Champion logo.",
    brand: "Champion",
    rating: 4.8,
    reviews: 900,
    stock: 150,
    colors: ["Black", "Gray", "Red", "White"],
  },
];

export default function Database() {
  async function updateDocs() {
    for (const product of products) {
      const ref = doc(collection(db, "products"), String(product.id));
      await setDoc(ref, product);
    }
  }
  updateDocs();
}
